version: '3'

services:
  web:
    image: claims-validation
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - migration
  migration:
    build: .
    image: claims-validation
    command: >
      bash -c "python manage.py makemigrations
      && python manage.py migrate"
    volumes:
      - .:/code
